let speedslow = false;
let speedmedium = false;
let speedfast = false;
let animationspeed = -1;

var container = document.getElementById("array");

// Function to generate the array of blocks
function generatearray() {
    for (var i = 0; i < 20; i++) {

        // Return a value from 1 to 100 (both inclusive)
        var value = Math.ceil(Math.random() * 100);

        // Creating element div
        var array_ele = document.createElement("div");

        // Adding class 'block' to div
        array_ele.classList.add("block");

        // Adding style to div
        array_ele.style.height = `${value * 3}px`;
        array_ele.style.transform = `translate(${i * 30}px)`;

        // Creating label element for displaying
        // size of particular block
        var array_ele_label = document.createElement("label");
        array_ele_label.classList.add("block_id");
        array_ele_label.innerText = value;

        // Appending created elements to index.html
        array_ele.appendChild(array_ele_label);
        container.appendChild(array_ele);
    }
}

// Promise to swap two blocks
function swap(el1, el2) {
    return new Promise((resolve) => {

        // For exchanging styles of two blocks
        var temp = el1.style.transform;
        el1.style.transform = el2.style.transform;
        el2.style.transform = temp;

        window.requestAnimationFrame(function() {
            // setTimeout is used for the speed of the animation. 
            // Fast-0 Medium-250 Slow-500
            setTimeout(() => {
                container.insertBefore(el2, el1);
                resolve();
            }, animationspeed);
        });
    });
}

// Asynchronous BubbleSort function
async function BubbleSort(delay = 0) {
    var blocks = document.querySelectorAll(".block");

    // BubbleSort Algorithm
    for (var i = 0; i < blocks.length; i += 1) {
        for (var j = 0; j < blocks.length - i - 1; j += 1) {

            // To change background-color of the
            // blocks to be compared
            blocks[j].style.backgroundColor = "#FF4949";
            blocks[j + 1].style.backgroundColor = "#FF4949";

            // To wait for .1 sec
            await new Promise((resolve) =>
                setTimeout(() => {
                    resolve();
                }, delay)
            );

            console.log("run");
            var value1 = Number(blocks[j].childNodes[0].innerHTML);
            var value2 = Number(blocks[j + 1]
                .childNodes[0].innerHTML);

            // To compare value of two blocks
            if (value1 > value2) {
                await swap(blocks[j], blocks[j + 1]);
                blocks = document.querySelectorAll(".block");
            }

            // Changing the color to the previous one
            blocks[j].style.backgroundColor = "#6b5b95";
            blocks[j + 1].style.backgroundColor = "#6b5b95";
        }

        //changing the color of greatest element
        //found in the above traversal
        blocks[blocks.length - i - 1]
            .style.backgroundColor = "#13CE66";
    }


    document.getElementById('slowbtn').disabled = false;
    document.getElementById('mediumbtn').disabled = false;
    document.getElementById('fastbtn').disabled = false;
    document.getElementById('genbtn').disabled = false;
    document.getElementById('startbtn').disabled = false;
}

function generateNewArray() {
    // This function is used to generate a new array containing elements of random numbers having random values.

    // We have to empty the msg written in the stop div block.
    document.getElementById('stopMessage').innerText = "";

    let divblock = document.getElementById('array');
    divblock.innerText = "";

    generatearray();
}

function startAnimation() {
    // This function is used for starting the animation of the array which is generated by the generate function.

    // We have to empty the msg written in the stop div block.
    document.getElementById('stopMessage').innerText = "";

    // First check if the speed of the animation is set if not then set it.
    if (animationspeed == -1)
        animationspeed = 250;

    // Now disable all the buttons leaving stop button if and only if array is generated in the div block.
    if (document.getElementById('array').innerText != "") {
        document.getElementById('slowbtn').disabled = true;
        document.getElementById('mediumbtn').disabled = true;
        document.getElementById('fastbtn').disabled = true;
        document.getElementById('genbtn').disabled = true;
        document.getElementById('startbtn').disabled = true;
        BubbleSort();
    }
}

function stopAnimation() {
    let msg = "";
    let divblock = document.getElementById('array');
    if (divblock.innerText != "") {
        document.getElementById('stopMessage').innerText = "Animation Stopped";
        document.getElementById('stopMessage').classList.add("stopMessageClass");
    }
    divblock.innerText = msg;

    document.getElementById('slowbtn').disabled = false;
    document.getElementById('mediumbtn').disabled = false;
    document.getElementById('fastbtn').disabled = false;
    document.getElementById('genbtn').disabled = false;
    document.getElementById('startbtn').disabled = false;


}

// Fast-0 Medium-250 Slow-500

function speedSlow() {
    speedslow = true;
    speedmedium = false;
    speedfast = false;

    animationspeed = 500;
}

function speedMedium() {
    speedslow = false;
    speedmedium = true;
    speedfast = false;

    animationspeed = 250;
}

function speedFast() {
    speedslow = false;
    speedmedium = false;
    speedfast = true;

    animationspeed = 0;
}